// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKSE_176TC2dOGZguAmJam6u19CZ_KI_A',
    appId: '1:368277681170:web:8f559c3954a888c97454cb',
    messagingSenderId: '368277681170',
    projectId: 'cavlog-officail',
    authDomain: 'cavlog-officail.firebaseapp.com',
    storageBucket: 'cavlog-officail.firebasestorage.app',
    measurementId: 'G-P7Z7BW7HWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9eBMdEF07VK0YpVuIzEj3tP9m4YyDp8g',
    appId: '1:368277681170:android:522fb5b19dbff8b87454cb',
    messagingSenderId: '368277681170',
    projectId: 'cavlog-officail',
    storageBucket: 'cavlog-officail.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNdLzZAC1gcDRvW3XkAzbrYmDXq-Yy9zE',
    appId: '1:368277681170:ios:de22e8461869c9107454cb',
    messagingSenderId: '368277681170',
    projectId: 'cavlog-officail',
    storageBucket: 'cavlog-officail.firebasestorage.app',
    iosBundleId: 'com.example.userPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNdLzZAC1gcDRvW3XkAzbrYmDXq-Yy9zE',
    appId: '1:368277681170:ios:de22e8461869c9107454cb',
    messagingSenderId: '368277681170',
    projectId: 'cavlog-officail',
    storageBucket: 'cavlog-officail.firebasestorage.app',
    iosBundleId: 'com.example.userPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKSE_176TC2dOGZguAmJam6u19CZ_KI_A',
    appId: '1:368277681170:web:0891e489cf914a277454cb',
    messagingSenderId: '368277681170',
    projectId: 'cavlog-officail',
    authDomain: 'cavlog-officail.firebaseapp.com',
    storageBucket: 'cavlog-officail.firebasestorage.app',
    measurementId: 'G-KKFSR3PXRB',
  );

}